services:
  db:
    image: mysql:latest
    container_name: local-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "nope"
      MYSQL_DATABASE: "forumapp"
    volumes:
      - /Users/Administrator/go/aesh/aesh_mysql/db:/var/lib/mysql
